travis:
  secure:
    BINSTAR_TOKEN: DmOnYoeOuq2KhR2z3lcjOziWuE/gPK1IdBCEfdz+whviICElrzXzE4HDg3QRLHeMLJfu2HfbIgszbGyjdKFUa2xOic6DgT0HjlYN4XZ/YN5Wiy9pzp3F6RKvauyEKMN9fWCg5QDKYrLyleoxcGSCt8TwfzKZFT1JHDHJSAYCd/dGf7vcmSjXAg2JfvQb63fD43FEog2aX3Bq8TpziOilyg0NIrSvD2DvcCBgx0yzuJAOUcjI0oP9FuVcDa/WkJ50OTfBTaldXqqIUMDOTx+1gW6MMbdB7k6TwbUYoxf+n1m7Q4l5nk6pzGFiNBIt0Wui2GamJUPAzqRRVvFGXm30PBX6aoK6AhgWAS+N7K9shhm4c4Yk3gYcwopKKuel8F7C/G418KCClyWQqpLovc8J4vLR/lsPeG1Aan2xO7C8hF4sHKXmIy9ikHBIV7gqZXwABUqLMqp7433Wa17dF8vaD1MxtrqwsdEHrTjTicS433tyMY7fLeXLCOsTRI00/SdPzvDpYqw6uMs5tSPq6KVoUJAv0ieoOELPe0y5xXTW9vdsd+kx724Op4GvHhk8ikPeJtLLvgI9pmTruqNgf7wVV2UNOPEkD27wA0fGEMZFcP/h/U2ZXVMWIArtbyQqJXehZgn3LbAU7pWJ24HtaVDYwrw+5mEtjAaaNMto2DdJD28=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
